-- AlterTable
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "defaultModelTemperature" DOUBLE PRECISION DEFAULT 0.7,
ADD COLUMN IF NOT EXISTS "researchModelTemperature" DOUBLE PRECISION DEFAULT 0.3,
ADD COLUMN IF NOT EXISTS "suggestionsModelTemperature" DOUBLE PRECISION DEFAULT 0.8;

