name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate Prisma client
        run: npx prisma generate
        
      - name: Build application
        run: npm run build
        
      - name: Create deployment package
        run: |
          # Create a tarball with necessary files
          tar -czf deploy.tar.gz \
            .next \
            package.json \
            package-lock.json \
            prisma \
            public \
            ecosystem.config.js \
            --exclude=node_modules
            
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: 22
          script: |
            # Create app directory if it doesn't exist
            mkdir -p /var/www/rogan-writer
            cd /var/www/rogan-writer
            
            # Stop the application
            pm2 stop rogan-writer || true
            pm2 delete rogan-writer || true
            
            # Backup current deployment
            if [ -d "current" ]; then
              rm -rf backup
              mv current backup
            fi
            
            # Create new deployment directory
            mkdir -p current
            
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: 22
          source: "deploy.tar.gz"
          target: "/var/www/rogan-writer/"
          
      - name: Extract and start application
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/rogan-writer
            
            # Extract the deployment package
            tar -xzf deploy.tar.gz -C current/
            cd current
            
            # Copy environment file from parent directory
            if [ -f "../.env" ]; then
              cp ../.env .env
            fi
            
            # Install only production dependencies
            npm ci --omit=dev
            
            # Run database migrations
            npx prisma migrate deploy
            
            # Start the application with PM2
            pm2 start ecosystem.config.js
            
            # Save PM2 configuration
            pm2 save
            
            # Show status
            pm2 status
            
            # Clean up
            rm ../deploy.tar.gz 